### ISSUE TITLE
wasmdome.dev down?

### ISSUE THREAD

**Issue by pretentious7** [wascc/wasmdome#25]
The site seems to be down rn.

**Comment by autodidaddict** [comment]
The site was only up for a live event and is no longer actively maintained.

**Comment by LiamRandall** [comment]
Just for reference, all of the old repo's and materials are available here:

https://github.com/wasmcloud/?q=wasmd&type=&language=


We're working on a large milestone atm, .15, which includes an update and refresh to documentation.

**Comment by pretentious7** [comment]
Ah ok, thx.
