### ISSUE TITLE
Wasmdome does not enforce 4 Action point rule

### ISSUE THREAD

**Issue by brooksmtownsend** [wascc/wasmdome#4]
Mechs are currently able to request more than 4 action points of actions per turn, and those actions will be executed as if there was no AP limit. The command processor should keep track of the actions that each mech performs each turn and limit these to a specified match action point limit.

**Comment by autodidaddict** [comment]
Or maybe the event sourcing module can keep track of that and simply reject/ignore any incoming action that would put a player over a variable-defined per-turn action limit that could be specified on the match start event? 

I think it just comes down to whether you consider the 4-point limit a game rule (which should be enforced by the `domain`/eventsourcing code) or an option of the command processor.

**Comment by brooksmtownsend** [comment]
One thing that I was also considering is if the 4-point limit is something we'd like to be able to change later, by match, so considering where that value would be stored. I think it is more of a game rule than a command processor responsibility, I'd like to update the mech template as well to include a list of actions they can take, and their required action points for transparency.

**Comment by autodidaddict** [comment]
It looks like a bunch of the parameters are created with the state's initial constructor, and aren't injected into the state via an event (this might be a refactor we want to do later?). 

https://github.com/wascc/wasmdome/blob/master/domaincommon/src/state.rs#L32

We could probably add a `max_ap_per_turn` field to the `MatchParameters` struct and then enforce it as turns are taken in the `domaincommon` crate.
